; ===== Common Settings for All ESP32 Devices =====
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/tomstewart89/BasicLinearAlgebra.git
board_upload.erase_flash = true
build_flags =
    -DCORE_DEBUG_LEVEL=5
    ; -DSPI_FREQ=80000000     ; <-- Set SPI 40 MHz

; ===== Server (COM6) =====
[env:server]
upload_port = COM6
monitor_port = COM6

; ===== Anchor (COM13) =====
[env:anchor]
upload_port = COM13
monitor_port = COM13

; ===== Client1 (COM9) =====
[env:client1]
upload_port = COM9
monitor_port = COM9

; ===== Client2 (COM11) =====
[env:client2]
upload_port = COM11
monitor_port = COM11

; ===== Client3 (COM12) =====
[env:client3]
upload_port = COM12
monitor_port = COM12

; ===== Client4 (COM10) =====
[env:client4]
upload_port = COM10
monitor_port = COM10

