[env:esp32dev-16mb]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
board_build.partitions = partitions/16MB.csv
lib_deps =
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/Links2004/arduinoWebSockets.git

[env:esp32dev-8mb]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
board_build.partitions = partitions/8MB.csv
lib_deps =
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/Links2004/arduinoWebSockets.git