#ifndef __API_CONFIG_H__
#define __API_CONFIG_H__

#define API_KERNEL_NAME "API"
#define API_KERNEL_STACK_SIZE 6400
#define API_KERNEL_PRIORITY 1
#define API_KERNEL_CORE 0
#define API_KERNEL_DELAY_TICKS 60
#define API_KERNEL_TRANSPORT_QUEUE_SIZE 16

#define API_WIFI_CONFIG_FILENAME "/wifi.cfg"
#define API_WIFI_CONFIG_DEFAULT_AP_SSID "esp32-uwb"
#define API_WIFI_CONFIG_DEFAULT_AP_PASS "12345678"

#define API_SERVER_CONFIG_FILENAME "/server.cfg"
#define API_SERVER_CONFIG_DEFAULT_MDNS "esp32-uwb"

#define API_UWB_CONFIG_FILENAME "/uwb.cfg"

#endif