#ifndef __UWBSERVER_CONFIG_H__
#define __UWBSERVER_CONFIG_H__

#define UWBSERVER_KERNEL_NAME "UWBServer"
#define UWBSERVER_KERNEL_STACK_SIZE 12000
#define UWBSERVER_KERNEL_PRIORITY 1
#define UWBSERVER_KERNEL_CORE 1
#define UWBSERVER_KERNEL_DELAY_TICKS 25
#define UWBSERVER_KERNEL_TRANSPORT_QUEUE_SIZE 16
#define UWBSERVER_KERNEL_TWR_UPDATE_QUEUE_SIZE 16

#endif