#ifndef __UWB_DEFINES_H__
#define __UWB_DEFINES_H__

#define UWB_FRAME_INDEX_CONTROL 0
#define UWB_FRAME_INDEX_SEQUENCE_NUMBER 2
#define UWB_FRAME_INDEX_NETWORK_ADDRESS 3
#define UWB_FRAME_INDEX_DESTINATION_ADDRESS 5
#define UWB_FRAME_INDEX_SOURCE_ADDRESS 7
#define UWB_FRAME_INDEX_FUNCTION_CODE 9
#define UWB_FRAME_INDEX_PAYLOAD 10
#define UWB_FRAME_INDEX_RANGING_REQRXTS 10
#define UWB_FRAME_INDEX_RANGING_RESTXTS 14

#define UWB_FUNCTION_CODE_AUTHORIZE 0x60
#define UWB_FUNCTION_CODE_NETWORK_UPDATE 0x61
#define UWB_FUNCTION_CODE_CLOCK_SYNC 0x62
#define UWB_FUNCTION_CODE_TDOA_ACCESS 0xA0
#define UWB_FUNCTION_CODE_TWR_ACCESS 0xB0
#define UWB_FUNCTION_CODE_TWR_REQUEST 0xB1
#define UWB_FUNCTION_CODE_TWR_RESPONSE 0xB2

#define UWB_RANGING_MODE_NONE 0x00
#define UWB_RANGING_MODE_TDOA 0x01
#define UWB_RANGING_MODE_TWR 0x02

#define DW3000_PIN_RST 27
#define DW3000_PIN_IRQ 34
#define DW3000_PIN_SS 4
#define DW3000_RX_ANTENNA_DELAY_UUS 16385
#define DW3000_TX_ANTENNA_DELAY_UUS 16385
#define DW3000_RX_AFTER_TX_DELAY_UUS 240
#define DW3000_RX_TIMEOUT_UUS 400
#define DW3000_FRAME_MAX_SIZE 127

#endif