#ifndef __UWBCLIENT_CONFIG_H__
#define __UWBCLIENT_CONFIG_H__

#define UWBCLIENT_KERNEL_NAME "UWBClient"
#define UWBCLIENT_KERNEL_STACK_SIZE 6400
#define UWBCLIENT_KERNEL_PRIORITY 2
#define UWBCLIENT_KERNEL_CORE 1
#define UWBCLIENT_KERNEL_DELAY_TICKS 25
#define UWBCLIENT_KERNEL_TRANSPORT_QUEUE_SIZE 16

#endif